<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>botonLupa</name>
   <tag></tag>
   <elementGuidId>bdc54d1c-a87a-4dcd-97ed-7928e9217d25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.normal[src='images/nav/search.png']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Search']/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
