<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SLROBOT_btn btn-softland-primary btnOk</name>
   <tag></tag>
   <elementGuidId>a9502f4e-731b-477e-a3fc-299d84cedd60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Aceptar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-softland-primary.btnOk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90d01034-5f3a-4d4b-a4b9-f5c696b28be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eafba3f6-7690-4a59-8587-172cb9fe48c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-softland-primary btnOk</value>
      <webElementGuid>16efabde-3350-4d01-90d2-a6edede2c146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>c9708663-788d-4b42-9202-9ca8e71e9bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DBAggregator&quot;)/div[@class=&quot;content&quot;]/div[@class=&quot;buttons&quot;]/input[@class=&quot;btn btn-softland-primary btnOk&quot;]</value>
      <webElementGuid>13181f8a-e0c4-4184-a667-fc814ac34f2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Aceptar']</value>
      <webElementGuid>3ce1c8d6-0b0e-42db-8ad0-a3851a71d013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DBAggregator']/div/div[2]/input</value>
      <webElementGuid>de3cec35-be7f-4b6f-9212-6a7b04d4641d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>9337d3c4-0b36-4460-83ef-d570db528ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>322db8c9-461b-48f0-b600-3b36efa1561b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
